#!/usr/bin/env sh

! cd "$(dirname "$0")" \
   && echo "Cannot change directory to $(basename "$0") script location" 1>&2 \
   && exit 1
echo "Updating the local repository in" `pwd`
find . -mindepth 1 -maxdepth 1 -type d \
   | cut -c3- \
   | xargs -n 1 -I DIRNAME dpkg-scanpackages DIRNAME DIRNAME/override \
   | gzip -c9 >Packages.gz
[ $? -ne 0 ] \
   && echo "Update failed" 1>&2 \
   && [ `id -u` -ne 0 ] && echo "Maybe you've forgotten to sudo?" 1>&2
